### ISSUE TITLE
[Feat][upgradinatorr] Ignore tags

### ISSUE THREAD

**Issue by Drazzilb08** [angrycuban13/Just-A-Bunch-Of-Starr-Scripts#3]
It would be useful (especially for sonarr integration) to be able to set tags to ignore either via ID or name. 

Ex.
Anime for example is for me at least done by hand, (for older anime especially), or kids shows are done by hand as well (what a nightmare most of them are).

**Comment by ahatdude** [comment]
To add onto this, it'd be nice if somehow we could ignore certain custom formats.
As an example, I've been seeing quite a few movies redownload just because it has that extra point for "freeleech" (as per trash's custom format weights). I'd love to be able to tell the script to ignore that since there's no need to redownload it.

Thanks!

**Comment by angrycuban13** [comment]
One of these days
